name: CI   

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Lister tout à la racine
        run: ls -la
      
      - name: Lister le contenu du jeu "Two Ships Passing"
        run: ls -la "Games/Two_Ships_Passing_The_Night"